## 딥러닝 파이토치 교과서 
### chapter 2  
#### 파이토치 기초 문법

#### 텐서 생성 및 변환

In [1]:
import torch
print(torch.tensor([[1,2],[3,4]])) # 2차원 형태의 텐서 생성 
print(torch.tensor([[1,2],[3,4]], device = "cuda:0")) # gpu에 텐서 생성 
print(torch.tensor([[1,2],[3,4]],dtype = torch.float64)) # dtype을 이용하여 텐서 생성

temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy()) # tensor를 넘파이 배열로 변환 

temp = torch.tensor([[1,2],[3,4]],device = "cuda:0")
print(temp.to("cpu").numpy()) #gpu상의 텐서를 cpu의 텐서로 변환한 후 넘파이 배열로 변환

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


#### 텐서의 인덱스 조작

In [2]:
temp = torch.FloatTensor([1,2,3,4,5,6,7]) #1차원 벡터 생성
print(temp[0],temp[1],temp[-1]) # 인덱스로 접근 
print("--------------------") 
print(temp[2:5],temp[4:-1]) #슬라이스로 접근 

tensor(1.) tensor(2.) tensor(7.)
--------------------
tensor([3., 4., 5.]) tensor([5., 6.])


#### 텐서 연산 및 차원 조작

In [3]:
v = torch.tensor([1,2,3]) 
w = torch.tensor([3,4,6]) 

print(w - v)

tensor([2, 2, 3])
